name: dfsupport
description: Delivery Fee Support
publish_to: "none"
version: 0.2.0+2
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
flutter:
  uses-material-design: true
